env                     = "dev"
location                = "eastus"
resource_group_name     = "rg-dev"
key_vault_name          = "kv-dev-rmg1-001"
storage_account_name    = "stdev001"
app_service_plan_name   = "asp-dev-001"
app_service_name        = "web-dev-001"
subnet_id               = "/subscriptions/1caa3d80-14f8-4775-b51b-247372d730b0/resourceGroups/rg-aiforce-hub-uksouth-001/providers/Microsoft.Network/virtualNetworks/vnet-aiforce-rmgpoc-uksouth-001/subnets/sbnt-pep-uksouth-001"
cosmosdb_name           = "cosmos-dev-001"
acr_name                = "acrdev001"
eventhub_namespace      = "ehns-dev-001"
eventhub_name           = "events-dev-001"
aad_client_secret_value = "REDACTED"
tags = {
  Owner = "rmg-devops"
  Env   = "dev"
}
