variable "location" {}
variable "resource_group_name" {}
variable "app_service_plan_name" {}
variable "app_service_name" {}
variable "env" {}
variable "cosmosdb_name" {}
variable "acr_name" {}
variable "storage_account_name" {}
variable "eventhub_namespace" {}
variable "eventhub_name" {}
variable "subnet_id" {}
variable "key_vault_name" {}
variable "tenant_id" {}
variable "aad_client_secret_value" {}
