env                     = "uat"
location                = "eastus"
resource_group_name     = "rg-uat"
key_vault_name          = "kv-uat-rmg-0011"
storage_account_name    = "stuat0012"
app_service_plan_name   = "asp-uat-001"
app_service_name        = "web-uat-001"
subnet_id               = "/subscriptions/1caa3d80-14f8-4775-b51b-247372d730b0/resourceGroups/rg-aiforce-hub-uksouth-001/providers/Microsoft.Network/virtualNetworks/vnet-aiforce-rmgpoc-uksouth-001/subnets/sbnt-pep-uksouth-001"
cosmosdb_name           = "cosmos-uat-0013"
acr_name                = "rmg-acruat001"
eventhub_namespace      = "ehns-uat-001"
eventhub_name           = "events-uat-001"
aad_client_secret_value = "REDACTED"
tags = {
  Owner = "rmg-uatops"
  Env   = "uat"
}
