name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (dev or uat)"
        required: true
        type: choice
        default: "dev"
        options:
          - dev
          - uat

permissions:
  contents: write
  pull-requests: write

env:
  TF_VERSION: 1.5.7

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      TF_WORKDIR: IAC/env/${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Clean Terraform cache
        run: |
          rm -rf ${{ env.TF_WORKDIR }}/.terraform
          rm -f ${{ env.TF_WORKDIR }}/.terraform.lock.hcl

      - name: Terraform Init
        run: terraform -chdir=${{ env.TF_WORKDIR }} init -reconfigure
        env:
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Validate
        run: terraform -chdir=${{ env.TF_WORKDIR }} validate

      - name: Run TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.55.0

      - name: Execute Terraform fmt
        run: terraform -chdir=${{ env.TF_WORKDIR }} fmt -check

      - name: Terraform Plan
        id: plan
        run: terraform -chdir=${{ env.TF_WORKDIR }} plan -var-file="${{ github.event.inputs.environment }}.tfvars" -out=tfplan
        env:
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ github.event.inputs.environment }}
          path: ${{ env.TF_WORKDIR }}/tfplan

  approval:
    needs: terraform
    runs-on: ubuntu-latest
    environment:
      name: approve-${{ github.event.inputs.environment }}
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Await Manual Approval
        run: echo "Waiting for approval before apply."

  terraform-apply:
    needs: approval
    runs-on: ubuntu-latest
    env:
      ENV: ${{ github.event.inputs.environment }}
      TF_WORKDIR: IAC/env/${{ github.event.inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan-${{ env.ENV }}
          path: ${{ env.TF_WORKDIR }}

      - name: Terraform Init
        run: terraform -chdir=${{ env.TF_WORKDIR }} init -reconfigure
        env:
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Apply - Stage 1 (Key Vault + Access Policies)
        run: |
          terraform -chdir=${{ env.TF_WORKDIR }} apply \
            -target=module.kv.azurerm_key_vault.kv \
            -target=module.kv.azurerm_key_vault_access_policy.terraform_sp \
            -target=module.kv.azurerm_key_vault_access_policy.provider_identity \
            -var-file="${{ env.ENV }}.tfvars" \
            -auto-approve
        env:
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Wait for Key Vault access policy propagation
        run: sleep 30

      - name: Terraform Plan - Stage 2 (Full Plan)
        run: terraform -chdir=${{ env.TF_WORKDIR }} plan -var-file="${{ env.ENV }}.tfvars" -out=tfplan
        env:
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Apply - Stage 2 (Full Apply)
        run: terraform -chdir=${{ env.TF_WORKDIR }} apply -auto-approve tfplan
        env:
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}