name: Create Terraform Storage Account

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy storage account"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - uat
          - prod

jobs:
  create-storage:
    name: Create Storage Account
    runs-on: ubuntu-latest
    env:
      ENV: ${{ github.event.inputs.environment }}
      LOCATION: eastus     # Change if needed
      RESOURCE_GROUP: rmg-infra
      CONTAINER: tfstate
    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Create Storage Account
      - name: Create Storage Account
        run: |
          #!/usr/bin/env bash
          set -e

          STORAGE_ACCOUNT="rmginfra${ENV}$(date +%s | sha256sum | head -c 6)"
          
          echo "Creating Resource Group: $RESOURCE_GROUP..."
          az group create --name "$RESOURCE_GROUP" --location "$LOCATION"

          echo "Creating Storage Account: $STORAGE_ACCOUNT..."
          az storage account create \
            --name "$STORAGE_ACCOUNT" \
            --resource-group "$RESOURCE_GROUP" \
            --location "$LOCATION" \
            --sku Standard_LRS \
            --kind StorageV2 \
            --encryption-services blob

          ACCOUNT_KEY=$(az storage account keys list --resource-group "$RESOURCE_GROUP" --account-name "$STORAGE_ACCOUNT" --query "[0].value" -o tsv)

          echo "Creating Blob Container: $CONTAINER..."
          az storage container create --name "$CONTAINER" --account-name "$STORAGE_ACCOUNT" --account-key "$ACCOUNT_KEY"

          echo "Storage account and container created successfully!"
          echo "Resource Group: $RESOURCE_GROUP"
          echo "Storage Account: $STORAGE_ACCOUNT"
          echo "Container: $CONTAINER"

      # Optionally, output backend config for Terraform
      - name: Save Backend Config
        run: |
          echo "storage_account_name=$STORAGE_ACCOUNT" >> backend.conf
          echo "container_name=$CONTAINER" >> backend.conf
          echo "key=terraform.tfstate" >> backend.conf
          echo "resource_group_name=$RESOURCE_GROUP" >> backend.conf
          
      # Upload backend.conf as artifact
      - name: Upload backend.conf
        uses: actions/upload-artifact@v3
        with:
          name: terraform-backend-config
          path: backend.conf
